# Generated by Django 4.1.2 on 2022-11-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recidencia',
            new_name='Residencia',
        ),
        migrations.RenameField(
            model_name='residencia',
            old_name='Num_recidencia',
            new_name='Num_residencia',
        ),
    ]
