# Generated by Django 4.1.2 on 2022-11-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_correspondencia_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_entregado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='Destino',
            field=models.IntegerField(null=True),
        ),
    ]
