# Generated by Django 4.1.2 on 2022-11-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_correspondencia_fecha_entregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
