# Generated by Django 4.1.2 on 2022-11-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_correspondencia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='Propietario',
            field=models.CharField(default='Hoteleria', max_length=30),
        ),
    ]
