# Generated by Django 4.1.2 on 2022-11-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_correspondencia_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='Destino',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
